name: omnimix_gui
description: "OmniMixPlayer GUI - Flutter frontend"
publish_to: "none"
version: 4.0.1+401

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  # HTTP + WebSocket
  http: ^1.2.0
  web_socket_channel: ^3.0.0
  url_launcher: ^6.3.1

  # Protobuf
  protobuf: ^6.0.0
  fixnum: ^1.1.0
  audio_service: ^0.18.18
  audio_service_win: ^0.0.3

  # Material You / Dynamic Color
  dynamic_color: ^1.7.0

  # Desktop
  desktop_multi_window: ^0.3.0
  window_manager: ^0.4.0
  system_tray: ^2.0.0
  process_run: ^1.1.0
  windows_single_instance: ^1.1.0

  # Storage
  shared_preferences: ^2.3.0
  ffi: ^2.2.0
  archive: ^4.0.9
  file_picker: ^11.0.2

  # State management
  flutter_riverpod: ^2.6.1
  win32: ^5.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
