<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AssemblyName>OmniMixPlayer.Backend</AssemblyName>
    <OutputPath>..\bin\Backend\</OutputPath>
    <RootNamespace>OmniMixPlayer.Backend</RootNamespace>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OmniMixPlayer.SDK\OmniMixPlayer.SDK.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FModBankParser" Version="1.2.0" />
    <PackageReference Include="Fmod5Sharp" Version="3.1.0" />
    <PackageReference Include="SubstreamSharp" Version="1.0.3" />
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.67.*" />
    <PackageReference Include="Grpc.AspNetCore.Web" Version="2.67.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.*" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.*" />
  </ItemGroup>

</Project>
